version: "3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    expose:
      - "5173"
    ports:
      - "5173:5173"
    env_file:
      - .env.production
    volumes:
      - ./src:/srv/app/frontend/src
      - ./index.html:/srv/app/frontend/index.html

