name: NodeJS with Vite

on:
  push:
    branches: [ "stage" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install depends
        run: |
          npm install --legacy-peer-deps

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: ${{ secrets.FRONT_PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}