name: Deploy stand
on:
  push:
    branches: [ "cicd-test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: 89.208.107.40
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_KEYPASS }}
            script: |
                cd ~/stand && docker-compose pull && docker-compose up -d