name: NodeJS with Vite

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: /var/www/AgylamFront
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_PUSER }}
        password: ${{ secrets.SSH_PASSWORD }}