name: Deploy stand
on:
  push:
    branches: [ "cicd-test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            # key: ${{ secrets.SSH_KEY }}
            # passphrase: ${{ secrets.SSH_KEYPASS }}
            script: |
                ls -la